input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ "Drone registered successfully" {
    mutate { add_field => { "event_type" => "drone_registration" } }
  } else if [message] =~ "Telemetry event ingested" {
    mutate { add_field => { "event_type" => "telemetry_update" } }
  } else if [message] =~ "Flight request approved" or [message] =~ "Flight request rejected" {
    mutate { add_field => { "event_type" => "flight_approval" } }
  } else if [message] =~ "Emergency" or [message] =~ "Low Battery" or [message] =~ "Communication Lost" {
    mutate { add_field => { "event_type" => "emergency_alert" } }
  } else if [log][level] == "error" {
    mutate { add_field => { "event_type" => "error_event" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "skynetx-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
