pipeline {
    agent any

    environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:/Applications/Docker.app/Contents/Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin:${env.PATH}"
        KUBECONFIG = "/Users/prathameshswami/.kube/config"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Tools') {
            steps {
                sh 'echo $PATH'
                sh 'which docker || true'
                sh 'python3 --version'
                sh 'docker --version'
                sh 'which kubectl || true'
                sh 'kubectl version --client'
                sh 'kubectl config current-context'
            }
        }

        stage('Install Python Dependencies') {
            steps {
                sh '''
                    python3 -m venv .venv
                    . .venv/bin/activate
                    python -m pip install --upgrade pip
                    python -m pip install -r requirements.txt
                '''
            }
        }

        stage('Run Basic Application Checks') {
            steps {
                sh '''
                    . .venv/bin/activate
                    python -m py_compile app.py
                '''
                sh '''
                    . .venv/bin/activate
                    python -c "from app import app; print(app.url_map)"
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t skynetx-app:1.0 .'
            }
        }

        stage('Apply Kubernetes Manifests') {
            steps {
                sh 'kubectl apply -f kubernetes/'
            }
        }

        stage('Verify Kubernetes Rollout') {
            steps {
                sh 'kubectl rollout status deployment/skynetx-app -n skynetx'
            }
        }

        stage('Show Pods and Service') {
            steps {
                sh 'kubectl get pods -n skynetx'
                sh 'kubectl get svc -n skynetx'
            }
        }
    }
}
